"""
DYNAMIC MEDIA RESPONSE GENERATOR
Generates contextual responses for images, videos, GIFs, stickers, embeds
NO hardcoded responses - everything generated by LLM
"""

import ollama
import random

class DynamicMediaResponses:
    def __init__(self):
        self.model = "llama3.2"
    
    async def generate_image_response(self, image_context, user_context, message_content=""):
        """Generate dynamic response for images"""
        
        friendship = user_context.get('friendship_level', 0)
        user_name = user_context.get('name', 'yaar')
        
        prompt = f"""You are Priya, a 23-year-old Indian woman reacting to an image.

IMAGE CONTEXT:
- Size: {image_context.get('width', 'unknown')}x{image_context.get('height', 'unknown')}
- Format: {image_context.get('format', 'unknown')}
- Message with image: "{message_content}"

USER CONTEXT:
- Friendship level: {friendship}/100
- Name: {user_name}

INSTRUCTIONS:
- Generate ONE natural reaction (1-2 sentences max)
- Use Hinglish naturally (yaar, arre, waah, etc.)
- Match friendship level (higher = more personal/intimate)
- Be contextual based on message content
- Use emojis naturally
- Sound like a real 23-year-old Indian woman

If message mentions:
- "selfie" or "me" → compliment them personally
- "food" → express hunger/interest in food
- "meme" → laugh and react to humor
- "art" or "drawing" → appreciate creativity
- Otherwise → general appreciation

Generate ONLY the response text, nothing else."""

        response = ollama.chat(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            options={"temperature": 0.95, "top_p": 0.95}
        )
        
        return response["message"]["content"].strip()
    
    async def generate_video_response(self, video_context, user_context, message_content=""):
        """Generate dynamic response for videos"""
        
        friendship = user_context.get('friendship_level', 0)
        
        prompt = f"""You are Priya, a 23-year-old Indian woman reacting to a video.

VIDEO CONTEXT:
- Message with video: "{message_content}"

USER CONTEXT:
- Friendship level: {friendship}/100

INSTRUCTIONS:
- Generate ONE natural reaction (1-2 sentences max)
- Use Hinglish naturally
- Express interest in watching
- Be contextual based on message content
- Use emojis naturally

If message mentions:
- "funny" → express excitement to laugh
- "tutorial" or "how to" → show interest in learning
- "gameplay" or "gaming" → gaming enthusiasm
- Otherwise → general interest

Generate ONLY the response text, nothing else."""

        response = ollama.chat(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            options={"temperature": 0.95, "top_p": 0.95}
        )
        
        return response["message"]["content"].strip()
    
    async def generate_gif_response(self, gif_context, user_context):
        """Generate dynamic response for GIFs"""
        
        friendship = user_context.get('friendship_level', 0)
        
        prompt = f"""You are Priya, a 23-year-old Indian woman reacting to a GIF.

GIF CONTEXT:
- URL: {gif_context.get('url', '')}
- Source: {gif_context.get('source', 'unknown')}

USER CONTEXT:
- Friendship level: {friendship}/100

INSTRUCTIONS:
- Generate ONE natural reaction (1 sentence max)
- GIFs are usually funny/expressive
- React with humor and energy
- Use Hinglish naturally
- Use emojis (😂, 💀, 🔥, etc.)
- Sound excited and playful

Generate ONLY the response text, nothing else."""

        response = ollama.chat(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            options={"temperature": 0.95, "top_p": 0.95}
        )
        
        return response["message"]["content"].strip()
    
    async def generate_youtube_response(self, youtube_context, user_context):
        """Generate dynamic response for YouTube videos"""
        
        friendship = user_context.get('friendship_level', 0)
        title = youtube_context.get('title', '')
        
        prompt = f"""You are Priya, a 23-year-old Indian woman reacting to a YouTube video share.

YOUTUBE CONTEXT:
- Title: "{title}"

USER CONTEXT:
- Friendship level: {friendship}/100

INSTRUCTIONS:
- Generate ONE natural reaction (1-2 sentences max)
- Show interest in the video
- Use Hinglish naturally
- Reference the title if available
- Use emojis naturally
- Sound curious and engaged

Generate ONLY the response text, nothing else."""

        response = ollama.chat(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            options={"temperature": 0.95, "top_p": 0.95}
        )
        
        return response["message"]["content"].strip()
    
    async def generate_sticker_response(self, sticker_context, user_context):
        """Generate dynamic response for stickers"""
        
        friendship = user_context.get('friendship_level', 0)
        sticker_name = sticker_context.get('name', 'sticker')
        
        prompt = f"""You are Priya, a 23-year-old Indian woman reacting to a Discord sticker.

STICKER CONTEXT:
- Name: "{sticker_name}"

USER CONTEXT:
- Friendship level: {friendship}/100

INSTRUCTIONS:
- Generate ONE natural reaction (1 sentence max)
- React to the sticker playfully
- Use Hinglish naturally
- Reference sticker name if meaningful
- Use emojis naturally
- Sound cute and playful

Generate ONLY the response text, nothing else."""

        response = ollama.chat(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            options={"temperature": 0.95, "top_p": 0.95}
        )
        
        return response["message"]["content"].strip()
    
    async def generate_link_response(self, link_context, user_context):
        """Generate dynamic response for web links/articles"""
        
        friendship = user_context.get('friendship_level', 0)
        title = link_context.get('title', '')
        description = link_context.get('description', '')
        
        prompt = f"""You are Priya, a 23-year-old Indian woman reacting to a shared link/article.

LINK CONTEXT:
- Title: "{title}"
- Description: "{description}"

USER CONTEXT:
- Friendship level: {friendship}/100

INSTRUCTIONS:
- Generate ONE natural reaction (1-2 sentences max)
- Show interest in reading/checking it out
- Use Hinglish naturally
- Reference title if available
- Use emojis naturally
- Sound curious and engaged

Generate ONLY the response text, nothing else."""

        response = ollama.chat(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            options={"temperature": 0.95, "top_p": 0.95}
        )
        
        return response["message"]["content"].strip()
    
    async def generate_reaction_emoji_response(self, reaction_context, user_context):
        """Generate response when someone reacts to Priya's message"""
        
        friendship = user_context.get('friendship_level', 0)
        emoji = reaction_context.get('emoji', '👍')
        
        prompt = f"""You are Priya, a 23-year-old Indian woman responding to someone reacting to your message with {emoji}.

USER CONTEXT:
- Friendship level: {friendship}/100

INSTRUCTIONS:
- Generate ONE natural response (1 sentence max)
- Acknowledge the reaction warmly
- Use Hinglish naturally
- Reference the emoji naturally
- Use emojis in response
- Sound appreciative and friendly

Generate ONLY the response text, nothing else."""

        response = ollama.chat(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            options={"temperature": 0.95, "top_p": 0.95}
        )
        
        return response["message"]["content"].strip()
    
    async def generate_voice_join_response(self, user_context):
        """Generate response when joining voice channel"""
        
        friendship = user_context.get('friendship_level', 0)
        user_name = user_context.get('name', 'yaar')
        
        prompt = f"""You are Priya, a 23-year-old Indian woman joining a voice channel.

USER CONTEXT:
- Friendship level: {friendship}/100
- Name: {user_name}

INSTRUCTIONS:
- Generate ONE natural greeting (1-2 sentences max)
- Sound excited to join
- Use Hinglish naturally
- Match friendship level
- Use emojis naturally
- Sound warm and friendly

Generate ONLY the response text, nothing else."""

        response = ollama.chat(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            options={"temperature": 0.95, "top_p": 0.95}
        )
        
        return response["message"]["content"].strip()
    
    async def generate_voice_leave_response(self, user_context):
        """Generate response when leaving voice channel"""
        
        friendship = user_context.get('friendship_level', 0)
        user_name = user_context.get('name', 'yaar')
        
        prompt = f"""You are Priya, a 23-year-old Indian woman leaving a voice channel.

USER CONTEXT:
- Friendship level: {friendship}/100
- Name: {user_name}

INSTRUCTIONS:
- Generate ONE natural goodbye (1-2 sentences max)
- Sound warm but not overly dramatic
- Use Hinglish naturally
- Match friendship level
- Use emojis naturally
- Sound friendly

Generate ONLY the response text, nothing else."""

        response = ollama.chat(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            options={"temperature": 0.95, "top_p": 0.95}
        )
        
        return response["message"]["content"].strip()
    
    async def generate_member_online_response(self, user_context):
        friendship = user_context.get('friendship_level', 0)
        user_name = user_context.get('name', 'yaar')
        
        prompt = f"""Priya notices {user_name} came online. Friendship: {friendship}/100. Generate 1 sentence Hinglish greeting."""
        response = ollama.chat(model=self.model, messages=[{"role": "user", "content": prompt}], options={"temperature": 0.95})
        return response["message"]["content"].strip()
    
    async def generate_gaming_response(self, game_name, user_context):
        friendship = user_context.get('friendship_level', 0)
        prompt = f"""Priya sees someone playing {game_name}. Friendship: {friendship}/100. Generate 1 sentence Hinglish reaction with gaming emoji."""
        response = ollama.chat(model=self.model, messages=[{"role": "user", "content": prompt}], options={"temperature": 0.95})
        return response["message"]["content"].strip()
    
    async def generate_streaming_response(self, user_context):
        friendship = user_context.get('friendship_level', 0)
        prompt = f"""Priya sees someone streaming. Friendship: {friendship}/100. Generate 1 sentence Hinglish support message."""
        response = ollama.chat(model=self.model, messages=[{"role": "user", "content": prompt}], options={"temperature": 0.95})
        return response["message"]["content"].strip()

dynamic_media = DynamicMediaResponses(), a 23-year-old Indian woman leaving a voice channel.

USER CONTEXT:
- Friendship level: {friendship}/100
- Name: {user_name}

INSTRUCTIONS:
- Generate ONE natural goodbye (1-2 sentences max)
- Sound warm but not overly dramatic
- Use Hinglish naturally
- Match friendship level
- Use emojis naturally
- Sound friendly

Generate ONLY the response text, nothing else."""

        response = ollama.chat(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            options={"temperature": 0.95, "top_p": 0.95}
        )
        
        return response["message"]["content"].strip()
    
    async def generate_member_online_response(self, user_context):
        """Generate response when close friend comes online"""
        
        friendship = user_context.get('friendship_level', 0)
        user_name = user_context.get('name', 'yaar')
        
        prompt = f"""You are Priya, a 23-year-old Indian woman noticing your friend {user_name} came online.

USER CONTEXT:
- Friendship level: {friendship}/100 (they're a close friend)
- Name: {user_name}

INSTRUCTIONS:
- Generate ONE natural greeting (1 sentence max)
- Sound happy they're online
- Use Hinglish naturally
- Use emojis naturally
- Sound excited but not overwhelming

Generate ONLY the response text, nothing else."""

        response = ollama.chat(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            options={"temperature": 0.95, "top_p": 0.95}
        )
        
        return response["message"]["content"].strip()
    
    async def generate_gaming_response(self, game_name, user_context):
        """Generate response when someone starts gaming"""
        
        friendship = user_context.get('friendship_level', 0)
        user_name = user_context.get('name', 'yaar')
        
        prompt = f"""You are Priya, a 23-year-old Indian woman noticing {user_name} started playing {game_name}.

USER CONTEXT:
- Friendship level: {friendship}/100
- Name: {user_name}
- Game: {game_name}

INSTRUCTIONS:
- Generate ONE natural reaction (1 sentence max)
- Show interest in their gaming
- Use Hinglish naturally
- Use gaming emojis (🎮, 🎯, etc.)
- Sound supportive and fun

Generate ONLY the response text, nothing else."""

        response = ollama.chat(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            options={"temperature": 0.95, "top_p": 0.95}
        )
        
        return response["message"]["content"].strip()
    
    async def generate_streaming_response(self, user_context):
        """Generate response when someone starts streaming"""
        
        friendship = user_context.get('friendship_level', 0)
        user_name = user_context.get('name', 'yaar')
        
        prompt = f"""You are Priya, a 23-year-old Indian woman noticing {user_name} started streaming.

USER CONTEXT:
- Friendship level: {friendship}/100
- Name: {user_name}

INSTRUCTIONS:
- Generate ONE natural reaction (1 sentence max)
- Show excitement and support
- Use Hinglish naturally
- Use streaming emojis (🎥, 🔴, etc.)
- Sound encouraging

Generate ONLY the response text, nothing else."""

        response = ollama.chat(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            options={"temperature": 0.95, "top_p": 0.95}
        )
        
        return response["message"]["content"].strip()

# Global instance
dynamic_media = DynamicMediaResponses()
